### ISSUE TITLE
01 - Header

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#1]
## Value Statement
As a **meal planner app**
I should have  **a header**
so that **the user knows which app he/she is using.**

## Description
![header](https://user-images.githubusercontent.com/76426580/197213392-25080729-4ca7-4816-aebe-13e62e7a4d6e.png)

## Acceptance criteria
- [x] there should be a header
- [x] inside a header should be a logo, a search button, and a favorites button
- [x] the logo, search button, and favorites button should be displayed in a row (buttons do not have functionality for now)

## Tasks
- [x] install react
- [x] remove default data
- [x] add header element
- [x] add search icon
- [x] add logo
- [x] add a heart or star button for liked items

## Size
small
