### ISSUE TITLE
05 - Card

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#10]
## Value statement

As a **user**
I would like **to see the basic information about a recipe**
so **I can easily tell if the recipe is, for example, interesting, takes a while to cook, or for how many people.**

## Description
<img width="298" alt="card" src="https://user-images.githubusercontent.com/76426580/197973832-142e6ad6-33ce-4126-a815-f1e58919fe48.png">

## Acceptance Criteria

- [x] there should be an image of the recipe
- [x] there should be the recipe name, servings, duration, and short description

## Tasks

- [x] create a `feat/card` branch locally
- [x] convert cards created in #8 into a card component 
- [x] display image on top of the card
- [x] display recipe name, servings, duration, and short description
- [x] add some card styling

## Size

small

**Comment by philmetscher** [comment]
Hey :)
Small hint:
As task 1 I would always write `create feature feat/FEATURENAME`

Everything else LGTM :)

**Comment by jecaps** [comment]
Thanks as always @philmetscher! 😁
