### ISSUE TITLE
07 - Favorites Page

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#15]
## Value statement

As a **user**
I would like **to see an overview of the items I liked**
so that **I can choose a recipe to cook from there**

## Description
<img width="379" alt="Favorites Page" src="https://user-images.githubusercontent.com/76426580/198208785-9effef4d-d073-4444-a056-f82150f0c23f.png">

## Acceptance Criteria

- [x] there should be a button that navigates to the favorites page when clicked
- [x] only liked items are displayed on the favorites page
- [x] item is removed from the page when the favorite button is clicked
- [x] the value of `favorite` key in the recipe object should be updated when removing an item from the page
- [x] the button should be in neutral color when the item is removed from the page

## Tasks

- [x] create a `feat/FavesPage` branch locally 
- [x] create a `Favorites` page
- [x] display liked items only 
- [x] add a button on either side of the header that directs the user to the Favorites Page when clicked

## Size

small
