### ISSUE TITLE
08 - Searchbar

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#16]
## Value statement

As a **user**
I want **to search for recipes**
so that **I can look for recipes I want to cook on a certain day**

## Description
<img width="374" alt="Search bar with suggested items" src="https://user-images.githubusercontent.com/76426580/198223435-7bb85553-79f0-4952-a399-f13969bba0f5.png">

## Acceptance Criteria

- [ ] there should be a search button with a search icon
- [ ] there should be a search input field when the search button is clicked
- [ ] there should be recipe suggestions once the user starts typing on the search field
- [ ] search bar should disappear when the `cancel` button is clicked

## Tasks

- [ ] create a `feat/searchbar` branch locally
- [ ] install and import fuzzy search
- [ ] create a `SearchBar` component
  - [ ] with an input-field
  - [ ] and a`CancelBtn` component 
    - [ ] add a function to hide the `SearchBar` component

## Size

medium

**Comment by AHen-C0de** [comment]
Hey,
some suggestions from my side:
- describe how you manage the display of the searchBar (maybe using a state & conditional rendering? What does the hide function do?)
- describe how you implement the search functionality with the fuzzy search (do you need an onChange callback to track the input?)
- where do the recipe data come from (a state? a DB request? ...)
