### ISSUE TITLE
08 - Recipe Details

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#18]
## Value statement

As a **user**
I want **to be directed to the recipe details**
so that **I can see all available information about the recipe**

## Description
![Screenshot 2022-10-27 at 16 47 01](https://user-images.githubusercontent.com/76426580/198321536-adae9a1a-9354-42d5-b230-b25a3f58e979.png)

## Acceptance Criteria

- [x] there should be an image displayed
- [x] Recipe name, preparation time, amount of servings, amount of ingredients, description, health score,  and instructions 
- [x] the amount of ingredient and the ingredient should be in separate columns
- [x] instructions should be shown in steps (example: Step 1: Boil water for n minutes.)

## Tasks

- [x] create a `feat/details` branch locally
- [x] create a `Details` Page to display all details of the recipe
- [x] create an `Instruction` component for each step of the instructions
- [x] create an `Ingredient` component for each ingredient
- [x] create a route that directs the user to the detail page when a recipe card is clicked
- [x] use context to use the recipe array from `App.js` in the detailed page

## Size
medium
