### ISSUE TITLE
09 - Add recipe to liked items when favorite button is clicked

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#19]
## Value statement

As a **user**
I would like **to have the option to add a recipe  from the `Detail` page**
after learning more about a recipe 

## Description

![Screenshot 2022-10-27 at 17 18 19](https://user-images.githubusercontent.com/76426580/198330209-23475c65-486e-4647-86aa-f8c10451387b.png)

## Acceptance Criteria

- [ ] An icon that changes color to red when clicked
- [ ] Recipe added from the details page should appear in the `Favorites` Page

## Tasks

- [ ] add the `FaveBtn` to the `Details` page
- [ ] update the value of `isFavorite` key when the button is clicked
- [ ] 

## Size

(small, medium, large)
