### ISSUE TITLE
02 - Navigation

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#2]
## Value Statement
As a user
I want to be able to switch pages with one click 
so that I have access to the main content.

## Description
![NavBar](https://user-images.githubusercontent.com/76426580/197219645-3b381167-0cf2-46dc-8187-f7f64bc15814.png)

## Acceptance criteria
- [x] there should be a navigation bar at the bottom of the screen
- [x] there should be four nav links
- [x] The four links should be displayed in a row
- [x] the home page should be the default page

## Tasks
- [x] add a nav element
- [x] insert four anchor tags in the nav element
- [x] apply display flex to the nav element
- [x] apply active styling to the home nav link

## Size
small
