### ISSUE TITLE
fetch and store data

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#20]
## Value statement

As a user, I want the items that I like to persist between page reloads so that I don't have to search for the recipe again

## Description
- liked items should still be on the favorites page even when the user closed the app

## Acceptance Criteria

- [x] liked recipes should not disappear from the favorites page when the page reloads or when the app was closed
- [x] favorite buttons of the items liked should still be red after reloading the page or the app is reopened

## Tasks

- [x] create a `feat/fetch-and-store-data` branch locally
- [x] use useEffect to fetch data from [Spoonacular API](https://spoonacular.com/food-api)
- [x] save the fetched data in a state in the `App.js`
- [x] create a `lib` folder and a `localStorage` file
- [x] in the `localStorage` file, add functions that save and load items fetched from the API

## Size
medium

**Comment by mpagels** [comment]
lgtm!
