### ISSUE TITLE
10 - Search Field

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#23]
## Value statement

As a **user**
I want **to be able to search for recipes**
so that **I can use them in the future**

## Description
![Screenshot 2022-10-28 at 16 45 15](https://user-images.githubusercontent.com/76426580/198655323-78f63bde-640a-4c13-add9-1c64e2192ecd.png)

## Acceptance Criteria

- [x] there should be a search button with a search icon
- [x] there should be a search input field when the search button is clicked
- [x] search input field should disappear when the `Cancel` button is clicked
- [x] card recipes should be displayed after submitting the search query

## Tasks

- [x] create a `feat/searchbar` branch locally
- [x] create a `SearchBtn` Component that shows the input field for searching
- [x] create a `Search` component 
- [x] create an input field and a cancel button that hides the input field
- [x] create a state for when to show and hide the search field and a function that toggles its value

## Size

small -> large
