### ISSUE TITLE
11 - Create Plan Form

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#25]
## Value statement

As a **user**
I want **to be able to schedule recipes**
so that **I can plan what to cook the next days**

## Description
<img width="641" alt="Screenshot 2022-10-31 at 14 23 50" src="https://user-images.githubusercontent.com/76426580/199018053-58258177-f321-4e83-a168-4d1dbcbfd58b.png">

## Acceptance Criteria

- [x] a button that adds a recipe to the schedule form
- [x] a form that allows to schedule of a recipe
- [x] a date picker, a dropdown button, and a confirm button that submits the form

## Tasks

- [x] create a `feat/create-plan` branch locally
- [x] create a `Form` component for scheduling recipes
- [x] create an `AddToPlanBtn` component to allow adding recipes from recipe cards or detail page
- [x] create a state to store chosen recipe for scheduling
- [x] create a state to store the schedule

## Size

medium
