### ISSUE TITLE
12 - Recipe Schedule Page

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#27]
## Value statement

As a **user**
I want **to see an overview of the recipes I have scheduled**
so that **I know when to cook which recipe**

## Description
![Schedule Page](https://user-images.githubusercontent.com/76426580/199187167-eb2e25cb-fa2d-4190-95ba-f32b6f19f08b.png)

## Acceptance Criteria
- [x] the date and day of the week
- [x] a card with the name of the recipe for each mealtime
- [x] should be directed to the recipe details page when a card is clicked
- [x] a button on the card that deletes a meal from the schedule
- [x] a button on the card that allows rescheduling of the meal

## Tasks

- [x] create a `feat/schedule page` branch locally
- [x] create a `SlotCard` component for each mealtime
- [x] display mealtime name and recipe name on a slot card
- [x] create a function that navigates to the recipe details when a slot card is clicked 
- [x] create a `RemoveBtn` component for deleting a meal slot
- [x] create an `EditBtn` component for rescheduling a meal

## Size

medium
