### ISSUE TITLE
03 - Routing 

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#3]
## Value statement
As a **navbar** 
I am **responsible for showing the available pages** 
so that **the user can easily navigate to them** 

## Description 

The navigation has four pages: 

- **A Home Page**, where the recipes for inspiration are displayed,
- **A Meal Planner Form**, where a recipe can be scheduled on a certain day and at a certain mealtime, 
- **A Meal Schedule**, where the scheduled meals of the week are displayed, and
- **A History Page**, where the history of the meal plan can be seen.

## Definition of Done
- [x] navigating between pages is possible

## Tasks
- [x] install react-router-dom
- [x] in the `index.js`, wrap `<App />` in `<BrowserRouter>` 
```js 
<BrowserRouter>
     <App />
</BrowserRouter>
```
- [x] create a `pages` folder and a file for each page (home, form, plan, and history)
- [x] add a "{pageName} is still under construction" text in each page file
- [x] replace the anchor tags with `NavLink` JSX element; do not forget to use the `to` attribute instead of `href`

## Size
small
