### ISSUE TITLE
14 - History Page

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#30]
## Value statement

As a **user**
I would like **to see the recipes I had in the past**
in order **to keep track of the food I have been eating**

## Description

<img width="394" alt="Screenshot 2022-11-04 at 12 51 39" src="https://user-images.githubusercontent.com/76426580/199966158-4b8d07c5-8c2b-4920-bd36-6b9146bf025b.png">

## Definition of Done

- [x] a text that indicates they are on the history page
- [x] dates should have passed
- [x] meals that were scheduled/assigned to the date
- [x] can schedule recipes from the history page
- [x] can visit recipe details from the history page

## Tasks

- [x] create a `feat/history page` branch locally
- [x] create a function that checks if a date has already passed
- [x] create a function that does not show the past dates in the `Meal Plan` page
- [x] create a function that only displays a schedule that has already passed in the `History` page
- [x] add buttons/links for scheduling or visiting the details page of a recipe from the history page

## Size

medium
