### ISSUE TITLE
15 - Form Modal

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#33]
## Value statement

As a **user**
I would like **a modal to pop up whenever I want to add or reschedule a recipe**
so that **I do not have to navigate to other pages to do it**

## Description
- Converting the `AddMealPlan` Page into a modal pop up

## Definition of Done

- [x] a modal that pops up whenever I want to add or reschedule a recipe
- [x] a modal that disappears when a `Cancel`, `Confirm`, or `Reschedule` button has been clicked

## Tasks

- [x] create a `feat/modal` branch locally
- [x] remove the `AddToPlan` Page and `Form` Component
- [x] create a `Modal` Component 
- [x] add form modal pop-ups to the `Home`, `Details`, `Favorites`, `Plan`, and `History` components
- [x] create a `Cancel` button that closes the modal

## Size

small-medium
