### ISSUE TITLE
16 - Testing

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#35]
## Value statement

As a **developer**
I should **do component and utility function testing**
so **I can detect errors that could pose bigger problems in the future**

## Description
- [x] 3 component tests
- [x] 2 utility function tests

## Definition of Done

- [x] tests should all pass

## Tasks

- [x] determine which components and functions to test
- [x] formulate tests

## Size

medium
