### ISSUE TITLE
17 - Clean styling code

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#37]
## Value statement

As a **developer**
I should **make sure that my code is clean**
so that **it would be easier for the reviewer to understand my code**

## Description
- cleaning styling code

## Definition of Done

- [x] styling code should be understandable
- [x] style-component variables should be used

## Tasks

- [x] replace all class selectors with separate styled-components variable 

## Size

medium
