### ISSUE TITLE
18 - Overwriting modal

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#39]
## Value statement

As a **user**
I want **to be alerted when I a meal has already been scheduled on a specific date and mealtime**
so that **I don't accidentally overwrite the schedule**

## Description
- a modal that appears on top of the add-to-plan modal 

## Definition of Done
- [ ] modal appears when a meal has already been assigned to a specific date

## Tasks
- [ ] create a `feat/overwrite` branch locally
- [ ] create an `Overwrite` component
- [ ] add text that alerts the user that he/she is trying to overwrite an assigned meal
- [ ] add a button that allows overwriting and another button to close the overwriting modal 

## Size
small - medium
