### ISSUE TITLE
18 -  App styling

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#40]
## Value statement

As a **user**
I need **the app to look appealing**
so that **I feel good using it**

## Description

- styling the app to make it look nice

## Definition of Done

- [ ] enhance user experience through adequate design
- [ ] use colors that complement each other

## Tasks

- [ ] restyle layout
- [ ] restyle `Details`, `Plan`, `History` Pages
- [ ] restyle all Card components

## Size
large
