### ISSUE TITLE
04 - Home Page

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#8]
## Value statement

As a **user**
I would like **to see recipes**
so that **I get an idea/inspiration for what I can cook in the next few days** 

## Description
![Home Page](https://user-images.githubusercontent.com/76426580/197223950-5cb6f8f2-93ae-4ca6-afb9-7e1af392f889.png)

## Acceptance Criteria
- [x] there should be a recipe card
- [x] the card should have an image, a recipe name, duration, servings, and a short description
- [x] there should be a "Recipes you might like" text at the top of the page

## Tasks
- [x] Add the text "Recipes you might like" on top of the cards list
- [x] Create a card with fake data
- [x] Display the card below the text from task 1 👆🏻

## Size
small

**Comment by sebsch1337** [comment]
Same here, you should write what a user wants to see :) In this case a home page that displays all the components.
Its actually a very small user story. But you can specify where to put the elements.

The last task should be an own user story for the card component.

**Comment by jecaps** [comment]
Hey @sebsch1337, thanks for the input. Creating a card component will come in the next user story 😬
