### ISSUE TITLE
06 - Favorites Button

### ISSUE THREAD

**Issue by jecaps** [jecaps/capstone-project-app#9]
## Value statement
As a **user**
 I want to **save recipes** 
so that **I have an overview of recipes that I like**

## Description
<img width="483" alt="favorite-button" src="https://user-images.githubusercontent.com/76426580/197352561-aee3fb3e-714c-4956-b69b-4d85362f8ae1.png">

## Acceptance criteria
- [x] there should be a button
- [x] the button should have an icon that 
      - changes to another color when clicked
      - changes the value of the `favorite` key in the recipe object

## Tasks

- [x] create a `feat/favebtn` branch locally
- [x] create a `FaveBtn` Component
- [x] create a function that
      - changes the color of the favorite icon from one to another, and
      - updates the value of the `favorite` key in the recipe object when clicked
- [x] add button to the top right of the  recipe card

## Size
small

**Comment by sebsch1337** [comment]
Your description hits the nail. Actually don't need a user story anymore :P

But... As a “favorite button": in our course we learned that we have to write as a user or developer in a user story. Maybe i'm wrong? But i would write like: _As a user, i want to save recipes, so that i have an overview of recipes that i like._

Acceptance Criteria
You could describe that there should be a button... and it should change its color when active... 
The story is a bit short. Maybe you can add more like _it should mark the recipe as bookmarked in your object_

Then in Tasks you could describe how to mark the recipe as bookmarked. :)

**Comment by jecaps** [comment]
Hey @sebsch1337, thanks! I have included your suggestion in the user story.
